inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  Exclude:
    - "vendor/**/*"
    - "bin/*"
    - "db/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"

Rails/FilePath:
  Exclude:
    - "config/environments/development.rb"

# 1行あたりの文字数をチェックする
Layout/LineLength:
  Exclude:
    - app/controllers/api/v1/pokemons_controller.rb
    - app/controllers/api/v1/users_controller.rb
    - config/initializers/devise.rb
# Assignment: 変数への代入
# Branch: メソッド呼び出し
# Condition: 条件文
# 上記項目をRubocopが計算して基準値を超えると警告を出す（上記頭文字をとって'Abc'）
Metrics/AbcSize:
  Max: 50

# メソッドの中身が複雑になっていないか、Rubocopが計算して基準値を超えると警告を出す
Metrics/PerceivedComplexity:
  Max: 8

# 循環的複雑度が高すぎないかをチェック（ifやforなどを1メソッド内で使いすぎている）
Metrics/CyclomaticComplexity:
  Max: 10

# メソッドの行数が多すぎないかをチェック
Metrics/MethodLength:
  Max: 30
  Exclude:
    - app/models/concerns/nature_data.rb
    - app/models/concerns/pokemon_data.rb

# ネストが深すぎないかをチェック（if文のネストもチェック）
Metrics/BlockNesting:
  Max: 5

# クラスの行数をチェック（無効）
Metrics/ClassLength:
  Enabled: false

# 空メソッドの場合に、1行のスタイルにしない NG例：def style1; end
Style/EmptyMethod:
  EnforcedStyle: expanded

# クラス内にクラスが定義されていないかチェック（無効）
Style/ClassAndModuleChildren:
  Enabled: false

# 日本語でのコメントを許可する
Style/AsciiComments:
  Enabled: false

# クラスやモジュール定義前に、それらの説明書きがあるかをチェック（無効）
Style/Documentation:
  Enabled: false

# ％i（）構文を使用していないシンボルで構成される配列リテラルをチェック（無効）
Style/SymbolArray:
  Enabled: false

# 文字列に値が代入されて変わっていないかチェック（無効）
Style/FrozenStringLiteralComment:
  Enabled: false

# メソッドパラメータ名の最小文字数を設定
Naming/MethodParameterName:
  MinNameLength: 1

# Moduleはデフォルトで100行までとなっているため、データ格納用に使っているModuleは除外している
Metrics/ModuleLength:
  Exclude:
    - app/models/concerns/nature_data.rb
    - app/models/concerns/pokemon_data.rb

# Contextの命名規則を無効（日本語では使いにくい）
RSpec/ContextWording:
  Enabled: false

# devise-token-auth によって作られたモデルは ActiveRecord::Base を継承しているが、これに対して警告が出てしまうため除外
Rails/ApplicationRecord:
  Exclude:
    - "app/models/user.rb"
