class NatureData < ActiveHash::Base
  self.data = [
    {
      id: 0,
      name: "がんばりや",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
    {
      id: 1,
      name: "さみしがり",
      stats: {
        hp: 1.0,
        attack: 1.1,
        defence: 0.9,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
    {
      id: 2,
      name: "ゆうかん",
      stats: {
        hp: 1.0,
        attack: 1.1,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 0.9,
      },
    },
    {
      id: 3,
      name: "いじっぱり",
      stats: {
        hp: 1.0,
        attack: 1.1,
        defence: 1.0,
        spAttack: 0.9,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
    {
      id: 4,
      name: "やんちゃ",
      stats: {
        hp: 1.0,
        attack: 1.1,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 0.9,
        speed: 1.0,
      },
    },
    {
      id: 5,
      name: "ずぶとい",
      stats: {
        hp: 1.0,
        attack: 0.9,
        defence: 1.1,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
    {
      id: 6,
      name: "すなお",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
    {
      id: 7,
      name: "のんき",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.1,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 0.9,
      },
    },
    {
      id: 8,
      name: "わんぱく",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.1,
        spAttack: 0.9,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
    {
      id: 9,
      name: "のうてんき",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.1,
        spAttack: 1.0,
        spDefence: 0.9,
        speed: 1.0,
      },
    },
    {
      id: 10,
      name: "おくびょう",
      stats: {
        hp: 1.0,
        attack: 0.9,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 1.1,
      },
    },
    {
      id: 11,
      name: "せっかち",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 0.9,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 1.1,
      },
    },
    {
      id: 12,
      name: "まじめ",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
    {
      id: 13,
      name: "ようき",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 0.9,
        spDefence: 1.0,
        speed: 1.1,
      },
    },
    {
      id: 14,
      name: "むじゃき",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 0.9,
        speed: 1.1,
      },
    },
    {
      id: 15,
      name: "ひかえめ",
      stats: {
        hp: 1.0,
        attack: 0.9,
        defence: 1.0,
        spAttack: 1.1,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
    {
      id: 16,
      name: "おっとり",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 0.9,
        spAttack: 1.1,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
    {
      id: 17,
      name: "れいせい",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 1.1,
        spDefence: 1.0,
        speed: 0.9,
      },
    },
    {
      id: 18,
      name: "てれや",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
    {
      id: 19,
      name: "うっかりや",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 1.1,
        spDefence: 0.9,
        speed: 1.0,
      },
    },
    {
      id: 20,
      name: "おだやか",
      stats: {
        hp: 1.0,
        attack: 0.9,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 1.1,
        speed: 1.0,
      },
    },
    {
      id: 21,
      name: "おとなしい",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 0.9,
        spAttack: 1.0,
        spDefence: 1.1,
        speed: 1.0,
      },
    },
    {
      id: 22,
      name: "なまいき",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 1.1,
        speed: 0.9,
      },
    },
    {
      id: 23,
      name: "しんちょう",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 0.9,
        spDefence: 1.1,
        speed: 1.0,
      },
    },
    {
      id: 24,
      name: "きまぐれ",
      stats: {
        hp: 1.0,
        attack: 1.0,
        defence: 1.0,
        spAttack: 1.0,
        spDefence: 1.0,
        speed: 1.0,
      },
    },
  ]

  include ActiveHash::Associations
  has_many :pokemons
  
end